### ISSUE TITLE
Issue Installing 

### ISSUE THREAD

**Issue by stamandster** [PiBrewing/cbpi4-iSpindle#9]
Issue as seen below

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting cbpi4-ispindle
  Downloading https://www.piwheels.org/simple/cbpi4-ispindle/cbpi4_iSpindle-0.0.13-py3-none-any.whl (17 kB)
WARNING: Error parsing dependencies of send2trash: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    sys-platform (=="darwin") ; extra == 'objc'
                 ~^
Installing collected packages: cbpi4-ispindle
Successfully installed cbpi4-ispindle-0.0.13

Though it says success, it does not show up in the console.

**Comment by avollkopf** [comment]
This is not related to the plugin but the system which is using an older version of send2trash. This issue is apparent for all plugins that are being installed in the venv, but does not affect the installation itself. Just tested it on my test system. To avoid the warning, you can install a newer version of send2trash in the cbpi4 venv:

`pipx runpip cbpi4 install send2trash==1.8.3`

**Comment by stamandster** [comment]
@avollkopf Thanks!
